steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '$(Build.DefinitionName)/**/*.csproj'
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'Codoxide@SonarCloud'
    organization: 'codoxide'
    scannerMode: 'MSBuild'
    projectKey: 'outcome'
    projectName: 'Outcome'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '$(Build.DefinitionName)/**/*.csproj'
    arguments: '--configuration Release'

- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '$(Build.DefinitionName)/*[Tt]ests/*.csproj'
    arguments: '--configuration Release'
- task: SonarCloudAnalyze@1
  enabled: false
- task: SonarCloudPublish@1
  enabled: false
  inputs:
    pollingTimeoutSec: '300'
- task: NuGetCommand@2
  displayName: 'NuGet push'
  inputs:
    command: push
    feedsToUse: config
    externalFeedCredentials: 'NuGet.org PAT'
    packagesToPush: '$(Build.SourcesDirectory)/$(Build.DefinitionName)/**/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: 'NuGet.org PAT'
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
